openapi: 3.0.3
info:
  title: Answers
  description: Answers is an API that allows interaction with an embeddings database.
  version: 1.0.0
  contact: {}
servers:
  - url: https://app.lindisfarne.nsw.edu.au
paths:
  /answers/:
    get:
      summary: Get
      description: Returns an array of docs with their access and tags.
      operationId: get
      parameters:
        - name: access
          in: query
          schema:
            type: string
            example: staff
          description: The access group the user performing the request is in. Default is 'public'.
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
    post:
      summary: Search
      description: Takes a string that is used to search for the closest matching docs in the embeddings database.
      operationId: search
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                  - text
              properties:
                text:
                  type: string
                  description: The text used in the search.
                  example: This is a test...
                access:
                  type: string
                  description: The access group that the user performing the search is in. Defaults to 'public'.
                  example: students
                limit:
                  type: number
                  description: The maximum number of docs to return.
                  example: 3
            examples:
              Search:
                value:
                  access: students
                  limit: 3
                  text: This is a test...
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
    put:
      summary: Insert
      description: Inserts an array of docs into the embeddings database.
      operationId: insert
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - docs
              properties:
                docs:
                  type: array
                  items:
                    type: string
                    example: Students must wear a tie in term 2 and term 3.
                  description: An array of strings that contain the content for each doc to be inserted.
                  example:
                    - Students must wear a tie in term 2 and term 3.
                access:
                  type: array
                  items:
                    type: string
                    example: 'students'
                  description: An array of strings that denote the groups that have access to these docs. Defaults to 'public'.
                tags:
                  type: array
                  items:
                    type: string
                    example: School Policies
                  description: An array of strings representing tags for the docs being inserted. Defaults to an empty array.
                  example:
                    - School Policies
                    - Technology
                    - IT
            examples:
              Insert:
                value:
                  access: []
                  docs:
                    - Students must wear a tie in term 2 and term 3.
                  tags:
                    - School Policies
                    - Technology
                    - IT
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
    delete:
      summary: Delete
      description: Delete
      operationId: delete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - ids
              properties:
                ids:
                  type: array
                  items:
                    type: string
                    example: '451335129797767456'
                  description: An array of ids to delete. Also takes a single id (as a string).
                  example:
                    - '451335129797767456'
            examples:
              Delete:
                value:
                  ids:
                    - '451335129797767456'
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
    patch:
      summary: Swap
      description: Swaps a current doc for a new doc.
      operationId: swap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - text
              properties:
                id:
                  type: string
                  description: The id of the doc currently in the embeddings database. This doc will be removed.
                  example: '451335129797767430'
                text:
                  type: string
                  description: The content of the new doc.
                  example: This is the new doc...
                access:
                  type: array
                  items:
                    type: string
                    example: staff
                  description: An array of strings that denote the groups that have access to these docs. Defaults to 'public'.
                  example:
                    - staff
                    - students
                tags:
                  type: array
                  items:
                    type: string
                    example: Test
                  description: An array of strings representing tags for the docs being inserted. Defaults to an empty array.
                  example:
                    - Test
            examples:
              Swap:
                value:
                  access:
                    - public
                  id: '451335129797767430'
                  tags:
                    - Test
                  text: This is a test...
      responses:
        '200':
          description: ''
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
tags: []
